### ISSUE TITLE
nodemon veraltet

### ISSUE THREAD

**Issue by BaerMitUmlaut** [ng-practice/api#1]
Aufgrund einer veralteten Version von nodemon lässt sich die API aktuell nicht ohne weiteres installieren: nodemon hängt indirekt vom Paket event-stream 3.3.6 ab, welches aufgrund einer Sicherheitslücke/Malware entfernt wurde.
https://github.com/ng-practice/api/blob/4b05a3d58c7fda39d2041b083f68c3c1012ec9f2/package.json#L52

Ein Upgrade auf 1.18.7 genügt.

**Comment by GregOnNet** [comment]
Vielen Dank für den Hinweis.
Fix in c484ce9.
